# Generated by Django 2.1.7 on 2019-04-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclovida',
            name='fase',
        ),
        migrations.DeleteModel(
            name='CicloVida',
        ),
        migrations.DeleteModel(
            name='Fase',
        ),
    ]
