# Generated by Django 2.1.7 on 2019-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloVida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ciclo de Vida',
                'verbose_name_plural': 'Ciclos de Vida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'ordering': ['nome'], 'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AddField(
            model_name='ciclovida',
            name='fase',
            field=models.ManyToManyField(blank=True, to='projeto.Fase', verbose_name='Fases'),
        ),
    ]
