# Generated by Django 2.1.7 on 2019-03-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20190327_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ciclo_vida',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='projeto.CicloVida', verbose_name='Ciclo de Vida'),
        ),
    ]
