# Generated by Django 2.1.7 on 2019-03-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_projeto_ciclo_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='instituicao',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='projeto.Instituicao'),
        ),
    ]
