# Generated by Django 2.1.7 on 2019-03-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_auto_20190328_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='ciclo_vida',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='plano_comunicacao',
        ),
    ]
