# Generated by Django 2.1.7 on 2019-03-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_projeto_plano_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='ciclo_vida',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='projeto.CicloVida', verbose_name='Ciclo de Vida'),
        ),
    ]
