# Generated by Django 2.1.7 on 2019-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_auto_20190328_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateTimeField(verbose_name='Data do fim'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data do inicio'),
        ),
    ]
