# Generated by Django 2.1.7 on 2019-03-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_auto_20190328_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='instituicao',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='projeto.Instituicao'),
        ),
    ]
