# Generated by Django 2.1.7 on 2019-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0010_auto_20190328_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('1', 'Concluido'), ('2', 'Em andamento'), ('3', 'Atrasado')], default='2', max_length=1, verbose_name='Status'),
        ),
    ]
